SELECT CITY, LENGTH(CITY) 
FROM STATION 
WHERE ID = (SELECT ID FROM (SELECT * FROM STATION ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 0,1) ST)
OR ID = (SELECT ID FROM (SELECT * FROM STATION ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 0,1) ST);